### ISSUE TITLE
Sorry to bother you ,how to use px2rem with this template?

### ISSUE THREAD

**Issue by byoungd** [dwqs/vue-startup#2]
I follow this link https://segmentfault.com/a/1190000011883121 to add px2rem-loader and change utils :
` 
# build/utils.js
 const px2remLoader = {
    [loaderKey]: 'px2rem-loader',
    [optionsKey]: {
      remUnit: 75
    }

  const loaders = [cssLoader, postcssLoader, lessLoader, stylusLoader, px2remLoader]`

`
# page/index.js
import 'lib-flexible'
`

but it didn't work.

Hope you can provider some tips, thanks a lot!
---
中文：根据这篇文章 https://segmentfault.com/a/1190000011883121 配置px2rem
在 build/utils.js 添加了px2rem-loader 但是并不生效
我在开发中css使用的是stylus,麻烦告知如何解决这个问题，感谢！

**Comment by dwqs** [comment]
@byoungd 改成  

```
build/utils.js
const loaders = [cssLoader, px2remLoader,  postcssLoader, lessLoader, stylusLoader]`
```

试试

**Comment by byoungd** [comment]
并不生效 
webpack.base.config.js 中有段注释

`
    // https://vue-loader.vuejs.org/en/configurations/extract-css.html
    // options: {
    //     loaders: {
    //         css: utils.extractCSS(),
    //         less: utils.extractCSS({
    //             lang: 'less'
    //         })
    //     }
    // }

`

是否与这个有关呢？

**Comment by dwqs** [comment]
我试了是可以的，我的步骤如下：

### 1 初始化项目

```js
chare init dwqs/vue-startup vue-webpack
// 用 vue-cli 一样
```

### 2 安装依赖

```js
cd  vue-webpack
npm i && npm i px2rem-loader -D
```

### 2 更改配置

```js
// build/utils.js
// ...

const px2remLoader = {
        [loaderKey]: 'px2rem-loader',
        [optionsKey]: {
            remUni: 75,
            remPrecision: 8
        }
    };

    const loaders = [cssLoader, postcssLoader, lessLoader];

    if (env === 'development') {
        return ['vue-style-loader'].concat(loaders);
    } else {
        return [cssLoader, px2remLoader, postcssLoader, lessLoader];
   }
// ...
```

然后 `npm run build`，查看 build 结果：

```
// dist/static/css/main.xxxx.css
h3{display:-ms-flexbox;display:flex;font-size:.24rem}.doc,a,h3{color:red}.doc,.time,a,h3{margin:.13333333rem}.time span:last-child{color:blue;cursor:pointer;padding-left:.13333333rem}.desc{color:blue;margin:.13333333rem}
```
